config/routes.rb
Rails.application.routes.draw do

  resources :styles
  root 'breweries#index'

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :users do
    post 'banned', on: :member
  end

  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer_club
  scope :confirmed, -> { where confirmed:true }
	scope :pending, -> { where confirmed:[nil,false] }

  validates_uniqueness_of :user_id, scope: :beer_club, message: "User is already a member of this club."

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @beer_clubs = BeerClub.all - current_user.beer_clubs
    # @beer_clubs = BeerClub.all.reject{ |club| current_user.in? club.members }
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user
    @membership.update_attribute :confirmed, false

    respond_to do |format|
      #if not current_user.beer_clubs.include? @membership.beer_club and @membership.save
      if @membership.save
        #current_user.memberships << @membership
        format.html { redirect_to beer_club_path(@membership.beer_club),
                      notice: "#{@membership.user.username}, you memberships is waiting for acceptance!" }
        format.json { render :show, status: :created, location: @membership }
      else
        @beer_clubs = BeerClub.all - current_user.beer_clubs
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership.beer_club, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1.
  # DELETE /memberships/1.json
  def destroy
    if current_user.beer_clubs.include? @membership.beer_club
      user = User.find_by id: @membership.user_id
      @membership.destroy
      respond_to do |format|
        format.html { redirect_to user_path(user), notice: "Membership in #{@membership.beer_club.name} is ended." }
        format.json { head :no_content }
      end
    end
  end

  def accept
    membership = Membership.find(params[:id])
    membership.update_attribute(:confirmed, true)
    redirect_to :back, notice:"Membership accepted for #{membership.user.username}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:beer_club_id, :user_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h2>New Membership</h2>

<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name) %>
  <%= f.submit %>
<% end %>


<!-- <%= render 'form' %>

<%= link_to 'Back', memberships_path %> -->

app/views/memberships/show.html.erb
<br>
<%= edit_and_destroy_buttons(@membership) %>