config/routes.rb
Rails.application.routes.draw do

  resources :styles
  root 'breweries#index'

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :users do
    post 'banned', on: :member
  end

  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage
  require 'securerandom'

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  has_secure_password

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30}

  validates :password, length: { minimum: 4},
                       format: { with: /([A-Z].*\d)|(\d.*[A-Z].*)/,
                         message: "has to have at least one number and one capital letter"}

   def self.top(n)
     User.all.sort_by{ |user| -user.ratings.count }.first(n)
   end

   def favorite_beer
     return nil if ratings.empty?
     ratings.sort_by{ |r| r.score }.last.beer
     # SQL query is alone faster, but causes n+1 problem
     # ratings.order(score: :desc).limit(1).first.beer
   end

   # Searches best average among different styles from user's ratings
   def favorite_style
     favorite :style
   end

   # Searches best average among different breweries from user's ratings
   def favorite_brewery
     favorite :brewery
   end

   def favorite(category)
     return nil if ratings.empty?
     # List all uniq categories that user has rated
     rated = ratings.map{ |r| r.beer.send(category) }.uniq
     # Calculate averages for those vategories with rating_of method,
     # sort the results and pick largest (last) average
     rated.sort_by { |item| -rating_of(category, item) }.first
   end

   # Calculate average rating for certain category
   def rating_of(category, item)
     ratings_of = ratings.select{ |r| r.beer.send(category) == item }
     ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
   end

   def self.create_user_with_omniauth(nick, provider)
      password = SecureRandom.base64
      #User.create(username: nick, password: password, password_confirmation: password)
      create! do |user|
        user.username = nick
        user.provider = provider
        user.password = password
        user.password_confirmation = password
      end
    end

   # Helper methods
   # private

   # Average rating method
   # def average(ratings)
     # ratings.inject(0.0){|sum, r| sum + r.score } / ratings.count
     # Alternative way
     # ratings.map(&:score).inject(&:+) / ratings.count.to_f
   # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @confirmed_memberships = Membership.confirmed.where(user_id: params[:id])
    @pending_memberships = Membership.pending.where(user_id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created. Sign in now!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      reset_session # or session[:user_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def banned
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)
    new_status = user.banned? ? "frozen" : "reactivated"
    redirect_to :back, notice:"User status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th> favorite beer </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td><%= user.favorite_beer %></td>
        <td>
          <% if user.banned %>
            <span class="label label-info label-xs">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="btn btn-info btn-sm">
  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2><%= @user.username %>
  <% if @user.admin  %>
    <span class="label label-info label-sm">admin</span>
  <% end %>
  <% if @user.banned  %>
    <span class="label label-info label-sm">Account frozen</span>
  <% end %>
  <% if current_user and current_user.admin and @user.banned %>
    <%= link_to "Reactivate account", banned_user_path(@user.id), method: :post, class: "btn btn-warning" %>
  <% elsif current_user and current_user.admin %>
    <%= link_to "Freeze account", banned_user_path(@user.id), method: :post, class: "btn btn-warning" %>
  <% end %>
</h2>

<% if @confirmed_memberships.any? %>
  <h3>Member of Beer clubs</h3>
    <ul>
      <% @confirmed_memberships.each do |member| %>
        <li><%= link_to member.beer_club, member.beer_club %></li>
      <% end %>
    </ul>
<% end %>

<% if @pending_memberships.any? %>
  <h3>Pending membership applications</h3>
    <ul>
      <% @pending_memberships.each do |member| %>
        <li><%= link_to member.beer_club, member.beer_club %></li>
      <% end %>
    </ul>
<% end %>

<% if @user.ratings.any? %>
  <h3>Ratings</h3>
  <p>
    <% if @user.ratings.any? %>
      Has made <%= pluralize(@user.ratings.size, 'rating') %>, average score: <%= @user.average_rating.round(1) %>
    <% end %>
  </p>

  <ol>
    <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %>
        <% if @user == current_user %>
          <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </li>
    <% end %>
  </ol>

  <h3>Favourites</h3>
  <p>
    Favourite style: <%= @user.favorite_style %>, brewery: <%= @user.favorite_brewery %>
  </p>

<% end %>


<% if @user == current_user %>
  <div class="btn btn-warning btn-sm">
    <%= link_to 'Edit', edit_user_path(@user) %>
  </div>
  <div class="btn btn-danger btn-sm">
    <%= link_to 'Delete this user', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>