config/routes.rb
Rails.application.routes.draw do

  resources :styles
  root 'breweries#index'

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :users do
    post 'banned', on: :member
  end

  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { only_integer: true }
  validate :acceptable_years

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  def self.top(n)
    Brewery.all.sort_by{ |b| -(b.average_rating || 0) }.first(n)
  end

  def acceptable_years
    if self.year < 1042
      errors.add(:year, "can't be that old!")
    end
    if self.year > Date.current.year
      errors.add(:year, "- We are not in the future yet, are we?")
    end
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2017
    puts "changed year to #{year}"
  end

  def to_s
    "#{name}"
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :only_admins, only: [:destroy]
  before_action :skip_if_cached, only:[:index]

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    order = params[:order] || 'name'

    if session[:sort_order] == 'desc'
      @active_breweries = case @order #order
      when 'name' then @active_breweries = Brewery.active.order(:name)
      when 'year' then @active_breweries = Brewery.active.order(:year)
      end

      @retired_breweries = case @order
      when 'name' then @retired_breweries = Brewery.retired.order(:name)
      when 'year' then @retired_breweries = Brewery.retired.order(:year)
      end
      session[:sort_order] = 'asc'
    else
      @active_breweries = case @order
      when 'name' then @active_breweries = Brewery.active.order(:name).reverse
      when 'year' then @active_breweries = Brewery.active.order(:year).reverse
      end

      @retired_breweries = case @order
      when 'name' then @retired_breweries = Brewery.retired.order(:name).reverse
      when 'year' then @retired_breweries = Brewery.retired.order(:year).reverse
      end
      session[:sort_order] = 'desc'
    end
    #Start RatingsJob asynchronically in the background
    RatingsJob.perform_async
  end

  def list
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>


<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing Breweries</h1>

<% if current_user and current_user.admin %>
  <div style="border-style: solid;">
    brewerylist-name: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name' ) %>
    <br>
    brewerylist-year: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-year' ) %>
    <br>
    current: <%= "brewerylist-#{@order}" %>
  </div>
<% end %>

<% cache "brewerylist-#{@order}", skip_digest: true do %>

  <h2>Active breweries</h2>
  <p> Number of active breweries: <%= @active_breweries.count %> </p>
  <%= render 'list', breweries: @active_breweries %>

  <h2>Retired breweries</h2>
  <p> Number of retired breweries: <%= @retired_breweries.count %> </p>
  <%= render 'list', breweries: @retired_breweries %>

<% end %>

<% if current_user%>
  <div class="btn btn-info btn-sm">
    <%= link_to 'Create a new brewery', new_brewery_path %>
  </div>
<% end %>
<div class="btn btn-info btn-sm">
  <%= link_to 'List of Beers', beers_path %>
</div>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
    <th> <a href="#" id="n_beers">Number of beers</a> </th>
    <th> <a href="#" id="active">Active</a> </th>
  </tr>
</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

  <h2><%= @brewery.name %>
    <% if not @brewery.active  %>
      <span class="label label-info label-sm">retired</span>
    <% end %>
  </h2>

  <p>
    <i>Established in <%= @brewery.year %></i>
  </p>

  <p>
    <strong>Number of beers:</strong> <%= @brewery.beers.count %>
  </p>

  <p>
    <% @brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %><br>
    <% end %>
  </p>

  <p>
    <% if @brewery.ratings.any? %>
      Has <%= pluralize(@brewery.ratings.size, 'rating') %>, average <%= @brewery.average_rating.round(1) %>
    <% end %>
  </p>

<% end %>


<p>
  <% if current_user and current_user.admin %>
    <%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
  <% end %>
</p>

<p>
  <%= edit_and_destroy_buttons(@brewery) %>
</p>